export const dataCasinos = [
  {
    id: '1',
    name: 'Spin City',
    url: 'https://spincityl.com/?trackCode=aff_022db3_31#Register',
    imgSource: '../../../../public/logos/logos-spincity.png',
    stars: 4.9,
    starsVoters: 897,
    bonus: ['50 PLN za rejestrację ','100% od depozytu + 100 Free Spinów'],
    payment: ['Visa', 'Mastercard', 'Maestro', 'Cirrus', 'Blik' , 'BankTransfer', 'Bitcoin', 'Usdt', 'Eth'],
  },
  {
    id: '2',
    name: 'Lemon',
    url: 'https://m.lemon.partners/Redirect.aspx?mid=10&sid=34&cid=&pid=&affid=21',
    imgSource: '../../../../public/logos/logos-lemoncasino.png',
    stars: 4.8,
    starsVoters: 721,
    bonus: ['400% od depozytu – wpłacasz 50 PLN dostajesz 250PLN na wszystkie gry MegaWays '],
    payment: ['Visa', 'Mastercard', 'Blik' , 'BankTransfer', 'Skrill', 'Jeton', 'Neteller', 'Trustly', 'Revolut', 'ApplePay', 'GooglePay', 'Neosurf', 'Paysafecard', 'Bitcoin', 'Ustd', 'Eth'],
  },
  {
    id: '3',
    name: 'MrBet',
    url: 'https://m.lemon.partners/Redirect.aspx?mid=10&sid=34&cid=&pid=&affid=21',
    imgSource: '../../../../public/logos/logos-mrbet.png',
    stars: 4.8,
    starsVoters: 588,
    bonus: ['50 PLN za rejestracę ','200% od depozytu + 100 Free Spinów'],
    payment: ['Visa', 'Mastercard', 'Maestro', 'Cirrus', 'Blik' , 'BankTransfer', 'Bitcoin', 'Usdt', 'Eth'],
  },
  {
    id: '4',
    name: 'Syndicate Casino',
    url: 'https://promo.syndicate1.casino/?lp=sn_wo_app2&trackCode=aff_a7d797_128',
    imgSource: '../../../../public/logos/logo-syndicatecasino.png',
    stars: 4.7,
    starsVoters: 612,
    bonus: ['10 EUR lub 50 PLN za rejestrację','100% od depozytu + 100 Free Spinów'],
    payment: ['Visa', 'Mastercard', 'Maestro', 'Cirrus', 'Blik' , 'BankTransfer', 'Bitcoin', 'Usdt', 'Eth'],
  },
  {
    id: '5',
    name: 'HotSlots',
    url: 'https://m.ewaffiliates.com/Redirect.aspx?mid=247&sid=541&cid=&pid=&affid=322',
    imgSource: '../../../../public/logos/logos-hotslots.png',
    stars: 4.7,
    starsVoters: 303,
    bonus: ['20 Free Spinów za rejestrację ','bonus 200% od depozytu  + 250 Free Spinów'],
    payment: ['Visa', 'Mastercard', 'Blik' , 'BankTransfer', 'Skrill', 'Neteller', 'Trustly', 'ecoPayz' , 'Paysafecard'],
  },
  {
    id: '6',
    name: 'Slottyway',
    url: 'https://referencemen.live/ktVmDV?c=0152VrRyzOcjQae350a8f033076b09',
    imgSource: '../../../../public/logos/logos-slottyway.png',
    stars: 4.6,
    starsVoters: 499,
    bonus: ['200% od depozytu + 50 Free Spinów'],
    payment: ['Visa', 'Mastercard', 'Blik' , 'BankTransfer', 'Jeton', 'Neosurf', 'eZeeWallet', 'Bitcoin', 'Usdt', 'Eth'],
  },
  {
    id: '7',
    name: 'Slottica',
    url: 'https://referencemen.live/ktVmDV?c=0144VrRyzOcjQa6b8562194ec69694',
    imgSource: '../../../../public/logos/logos-slottica.png',
    stars: 4.6,
    starsVoters: 492,
    bonus: ['5 EURO za rejestrację ','200% od depozytu + 30 Free Spinów'],
    payment: ['Visa', 'Mastercard', 'Blik' , 'BankTransfer', 'Jeton', 'Neosurf', 'eZeeWallet', 'Bitcoin', 'Usdt', 'Eth'],
  },
  {
    id: '8',
    name: 'Spinamba',
    url: 'https://referencemen.live/ktVmDV?c=0147VrRyzOcjQa43eb22e25ad5f126',
    imgSource: '../../../../public/logos/logos-spinamba.png',
    stars: 4.6,
    starsVoters: 578,
    bonus: ['20 PLN za rejestrację','100% od depozytu + 100 Free Spinów'],
    payment: ['Visa', 'Mastercard', 'Blik' , 'BankTransfer', 'Jeton', 'Neosurf', 'eZeeWallet', 'Bitcoin', 'Usdt', 'Eth'],
  },
  {
    id: '9',
    name: 'Wazamba',
    url: 'https://wzb-bc-7s.lptrak.com/redirect.aspx?pid=2062112&lpid=2034&bid=5397',
    imgSource: '../../../../public/logos/logos-wazamba.png',
    stars: 4.6,
    starsVoters: 289,
    bonus: ['100% od depozytu ','200 Free Spinów + 1 CrabBonus'],
    payment: ['Visa', 'Mastercard', 'Blik' , 'BankTransfer', 'Jeton' , 'Revolut', 'ApplePay', 'GooglePay', 'Bitcoin', 'Usdt', 'Eth'],
  },
  {
    id: '13',
    name: '5 Gringos',
    url: 'https://5g.lp247p.com/C.ashx?btag=a_7526b_427c_&affid=1845&siteid=7526&adid=427&c=',
    imgSource: '../../../../public/logos/logos-5gringos.png',
    stars: 4.5,
    starsVoters: 216,
    bonus: ['100% od depozytu','200 Free Spinów + 1 CrabBonus'],
    payment: ['Visa', 'Mastercard', 'Blik' , 'BankTransfer', 'Revolut', 'Neosurf', 'eZeeWall', 'Bitcoin', 'Usdt', 'Eth'],
  },
  {
    id: '14',
    name: 'GGbet',
    url: 'https://ggbethype.com/l/611fc20404d1e34cc31e0ee1',
    imgSource: '../../../../public/logos/logos-ggbet.png',
    stars: 4.5,
    starsVoters: 890,
    bonus: ['200% od depozytu + 50 Free Spinów'],
    payment: ['Visa', 'Mastercard', 'Blik' , 'BankTransfer', 'Skrill', 'Neosurf', 'Neteller', 'Bitcoin', 'Usdt', 'Eth'],
  },
  {
    id: '15',
    name: 'Vulkan Vegas',
    url: 'https://happywithvegas.com/l/616d85006ebf5179e97ee105',
    imgSource: '../../../../public/logos/logos-vulcanvegas.png',
    stars: 4.4,
    starsVoters: 776,
    bonus: ['100% od depozytu + 25 Free Spinów'],
    payment: ['Visa', 'Mastercard', 'Blik' , 'BankTransfer', 'Skrill', 'Neosurf', 'Neteller' , 'Trustly', 'Bitcoin', 'Usdt', 'Eth'],
  },
  {
    id: '16',
    name: 'Ice Casino',
    url: 'https://icepromo.info/l/61c1d1979e2c6d24f351063c',
    imgSource: '../../../../public/logos/logos-icecasino.png',
    stars: 4.4,
    starsVoters: 503,
    bonus: ['120 % od depozytu + 120 Free Spinów'],
    payment: ['Visa', 'Mastercard', 'Blik' , 'BankTransfer', 'Skrill', 'Neosurf', 'Neteller' , 'Trustly', 'Bitcoin', 'Usdt', 'Eth'],
  },
  {
    id: '17',
    name: 'Haz Casino',
    url: 'https://www.hazcasino.com/?a_aid=TotalCasinoFB',
    imgSource: '../../../../public/logos/logos-hazcasino.png',
    stars: 4.4,
    starsVoters: 165,
    bonus: ['250% od depozytu + 125 Free Spinów'],
    payment: ['Visa', 'Mastercard', 'Blik' , 'BankTransfer', 'Skrill', 'Neteller', 'Jeton', 'Neosurf', 'Bitcoin', 'Usdt', 'Eth'],
  },
  {
    id: '18',
    name: 'Neon54',
    url: 'https://n54-bc-mio.lptrak.com/redirect.aspx?pid=2070632&lpid=16123&bid=8275',
    imgSource: '../../../../public/logos/logos-neon54.png',
    stars: 4.3,
    starsVoters: 341,
    bonus: ['100% od depozytu + 1 CrabBonus'],
    payment: ['Visa', 'Mastercard', 'Maestro', 'Blik' , 'BankTransfer', 'Neosurf', 'Neteller', 'eZeeWallet',  'Bitcoin', 'Usdt', 'Eth'],

  },
  {
    id: '19',
    name: 'Foggy Star',
    url: 'https://foggylink.com/d490635b4',
    imgSource: '../../../../public/logos/logos-foggystar.png',
    stars: 4.3,
    starsVoters: 147,
    bonus: [' 100% od depozytu + 50 Free Spinów '],
    payment: ['Visa', 'Mastercard', 'Blik' , 'BankTransfer', 'Skrill', 'Neosurf', 'Neteller' , 'eZeeWallet', 'Jeton', 'Paysafecard', 'Bitcoin', 'Usdt', 'Eth'],
  },
  {
    id: '20',
    name: 'Bizzo',
    url: 'https://ajie23.info/redirect.aspx?pid=176960&bid=2058&lpid=1047',
    imgSource: '../../../../public/logos/logos-bizzo.png',
    stars: 4.3,
    starsVoters: 309,
    bonus: ['100% od depozytu + 100 Free Spinów'],
    payment: ['Visa', 'Mastercard' , 'BankTransfer', 'Skrill', 'Jeton', 'Neteller', 'Bitcoin', 'Eth'],
  },
  {
    id: '21',
    name: 'Wolfy Casino',
    url: 'https://record.wolfyaffiliates.com/_tF5oe9SFAYaZM7hnoUx_dWNd7ZgqdRLk/1/',
    imgSource: '../../../../public/logos/logos-wolfycasino.png',
    stars: 4.3,
    starsVoters: 206,
    bonus: ['100% od depozytu (WAGER Free)'],
    payment: ['Visa', 'Mastercard', 'Blik' , 'BankTransfer', 'Skrill', 'Neteller' , 'Jeton' , 'Paysafecard', 'Bitcoin', 'Usdt', 'Eth'],
  },
  {
    id: '22',
    name: 'Rabona',
    url: 'https://rbn-bc-7s.lptrak.com/redirect.aspx?pid=2062113&lpid=14487&bid=6630',
    imgSource: '../../../../public/logos/logos-rabona.png',
    stars: 4.2,
    starsVoters: 255,
    bonus: ['100% od depozytu','200 Free Spinów + 1 CrabBonus'],
    payment: ['Visa', 'Mastercard', 'Blik' , 'BankTransfer', 'eZeeWallet', 'ApplePay', 'Revolut', 'Jeton',  'Bitcoin', 'Usdt', 'Eth'],
  },
  {
    id: '23',
    name: 'Thor Casino',
    url: 'http://www.thorcasino.com/?a_aid=ThorCasinoPolska&a_bid=e8c36587',
    imgSource: '../../../../public/logos/logos-thorcasino.png',
    stars: 4.2,
    starsVoters: 132,
    bonus: ['100% od depozytu + 25 Free Spinów (WAGER Free)'],
    payment: ['Visa', 'Mastercard', 'Blik' , 'BankTransfer', 'eZeeWallet', 'Jeton',  'Bitcoin', 'Usdt', 'Eth'],
  },
  {
    id: '24',
    name: 'HellSpin',
    url: 'https://media.hellpartners.com/redirect.aspx?pid=3979&bid=1466&lpid=28',
    imgSource: '../../../../public/logos/logos-hellspin.png',
    stars: 4.2,
    starsVoters: 598,
    bonus: ['100% od depozytu + 100 Free Spinów'],
    payment: ['Visa', 'Mastercard', 'Blik' , 'BankTransfer', 'Skrill', 'Neteller', 'Jeton',  'Bitcoin', 'Usdt', 'Eth'],
  },
  
  // {
  //   id: '7',
  //   name: 'Slots Palace',
  //   url: 'https://sp-bc-mio.lptrak.com/redirect.aspx?pid=2070632&lpid=16263&bid=8446'
  // },
  
 
  // {
  //   id: '14',
  //   name: 'Light Casino',
  //   url: 'https://ltc-bc-7s.lptrak.com/redirect.aspx?pid=2062103&lpid=15028&bid=7066'
  // },
  
  
  
  
  // {
  //   id: '19',
  //   name: 'Sportaza',
  //   url: 'https://st.lp247p.com/C.ashx?btag=a_7526b_546c_&affid=1845&siteid=7526&adid=546&c='
  // },
  
  // {
  //   id: '21',
  //   name: 'CasinoMega',
  //   url: 'https://record.gambaffpartners.com/_k74rHDZuHnf6PBA04iUMN2Nd7ZgqdRLk/1/'
  // },
  
  
  // {
  //   id: '24',
  //   name: 'Energy',
  //   url: 'https://charity.energy.partners/redirect.aspx?pid=37431&bid=5392'
  // },
  // {
  //   id: '25',
  //   name: 'ivibet',
  //   url: 'https://media.hellpartners.com/redirect.aspx?pid=3979&bid=1478&lpid=47'
  // },
  
  // {
  //   id: '27',
  //   name: '20 Bet',
  //   url: 'https://clikg5.info/redirect.aspx?pid=176960&bid=1971&lpid=420'
  // }
]